version: "3"
services:
  manager:
    build:
      context: "./app"
      dockerfile: "Dockerfile.txt"
    environment: 
        CSV_FILENAME: "data.csv"
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "secret"
      CSV_FILENAME: "data.csv"
